name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.KEY_NAME }}
          aws-secret-access-key: ${{ secrets.SECRET_KEY_NAME }}
          aws-region: eu-north-1
      - name: Copy to S3
        run: aws s3 sync . s3://fac30unschoolawstutorial.co.uk --delete
